name: Check documentation snippets

on:
  release:
    types: [published]
    

jobs:
  notifiy-snippets-repository:

    runs-on: ubuntu-latest
    steps:
      - name: Call curl
        run: | 
              curl -XPOST -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/GetStream/docs-snippets-android/dispatches --data '{"event_type": "check-on-new-release"}'
